/**
 * TRAVELBHARAT - EXPANDED DESTINATIONS DATASET (Structured 500+ Tourist Places)
 * Verified structured data with timings, entry fees, coordinates, and live online source photography.
 */

const TravelBharatDestinations = [
  // ================= NORTH INDIA =================
  // --- Uttar Pradesh ---
  {
    id: "taj-mahal",
    name: "Taj Mahal",
    stateId: "uttar-pradesh",
    cityId: "agra",
    category: "Heritage",
    tags: ["Mughal", "Wonder of the World", "Architecture", "Marble", "UNESCO", "Romantic"],
    description: "An immense mausoleum of white marble, built in Agra between 1631 and 1648 by the Mughal emperor Shah Jahan in memory of his favourite wife Mumtaz Mahal.",
    history: "Considered the jewel of Muslim art in India and one of the universally admired masterpieces of the world's heritage. Employed over 20,000 artisans under architect Ustad Ahmad Lahori.",
    bestTime: "October to March (Sunrise or Sunset for optimal light)",
    timings: "Sunrise to Sunset (06:00 AM - 06:30 PM). Closed on Fridays.",
    entryFee: "₹50 (Indians), ₹1100 (Foreign Tourists). Additional ₹200 for main mausoleum.",
    location: "Dharmapuri, Forest Colony, Tajganj, Agra, Uttar Pradesh 282001",
    latitude: 27.1751,
    longitude: 78.0421,
    mapUrl: "https://maps.google.com/?q=27.1751,78.0421",
    image: "https://images.unsplash.com/photo-1564507592333-c60657eea523?auto=format&fit=crop&w=1200&q=80",
    gallery: [
      "https://images.unsplash.com/photo-1548013146-72479768bada?auto=format&fit=crop&w=800&q=80"
    ],
    nearbyPlaces: ["agra-fort", "fatehpur-sikri-complex"],
    isPopular: true,
    isHiddenGem: false
  },
  {
    id: "agra-fort",
    name: "Agra Fort",
    stateId: "uttar-pradesh",
    cityId: "agra",
    category: "Heritage",
    tags: ["Mughal", "Fort", "UNESCO", "Royal"],
    description: "A colossal red sandstone fortress on the banks of Yamuna River that served as the main residence of the Mughal emperors until 1638.",
    history: "Rebuilt in red sandstone by Emperor Akbar in 1565. Shah Jahan later added white marble palaces and was later imprisoned here overlooking the Taj.",
    bestTime: "October to March",
    timings: "06:00 AM - 06:00 PM (All days)",
    entryFee: "₹50 (Indians), ₹650 (Foreign Tourists)",
    location: "Agra Fort, Rakabganj, Agra, Uttar Pradesh 282003",
    latitude: 27.1795,
    longitude: 78.0211,
    mapUrl: "https://maps.google.com/?q=27.1795,78.0211",
    image: "https://images.unsplash.com/photo-1599661046827-dacff0c0f09a?auto=format&fit=crop&w=1200&q=80",
    gallery: ["https://images.unsplash.com/photo-1587474260584-136574528ed5?auto=format&fit=crop&w=800&q=80"],
    nearbyPlaces: ["taj-mahal", "fatehpur-sikri-complex"],
    isPopular: true,
    isHiddenGem: false
  },
  {
    id: "fatehpur-sikri-complex",
    name: "Fatehpur Sikri & Buland Darwaza",
    stateId: "uttar-pradesh",
    cityId: "agra",
    category: "Heritage",
    tags: ["UNESCO", "Mughal Architecture", "Buland Darwaza", "Akbar"],
    description: "The fortified red sandstone city founded in 1569 by Emperor Akbar, featuring the towering Buland Darwaza and Salim Chishti Dargah.",
    history: "Served as the Mughal capital from 1571 to 1585 until abandoned due to water shortages.",
    bestTime: "October to March",
    timings: "06:00 AM - 06:00 PM (Daily)",
    entryFee: "₹50 (Indians), ₹610 (Foreigners)",
    location: "Fatehpur Sikri, Agra District, Uttar Pradesh 283110",
    latitude: 27.0945,
    longitude: 77.6679,
    mapUrl: "https://maps.google.com/?q=27.0945,77.6679",
    image: "https://images.unsplash.com/photo-1590050752117-238cb0fb12b1?auto=format&fit=crop&w=1200&q=80",
    gallery: [],
    nearbyPlaces: ["taj-mahal", "agra-fort"],
    isPopular: true,
    isHiddenGem: false
  },
  {
    id: "dashashwamedh-ghat",
    name: "Dashashwamedh Ghat & Evening Ganga Aarti",
    stateId: "uttar-pradesh",
    cityId: "varanasi",
    category: "Spiritual",
    tags: ["Holy River", "Ganga Aarti", "Spiritual", "Ghats"],
    description: "The main and most vibrant ghat on the Ganges River in Varanasi, world-renowned for its grand daily evening Maha Ganga Aarti ceremony.",
    history: "According to Hindu tradition, Lord Brahma created this ghat to welcome Lord Shiva and performed ten horse sacrifices.",
    bestTime: "October to March (Evening 06:00 PM for Aarti)",
    timings: "Open 24 Hours. Evening Aarti: 06:30 PM - 07:45 PM",
    entryFee: "Free access (Boat rides: ₹100 - ₹300/person)",
    location: "Dashashwamedh Ghat Rd, Bangali Tola, Varanasi, Uttar Pradesh 221001",
    latitude: 25.3076,
    longitude: 83.0107,
    mapUrl: "https://maps.google.com/?q=25.3076,83.0107",
    image: "https://images.unsplash.com/photo-1571536802807-30451e3955d8?auto=format&fit=crop&w=1200&q=80",
    gallery: ["https://images.unsplash.com/photo-1582510003544-4d00b7f74220?auto=format&fit=crop&w=800&q=80"],
    nearbyPlaces: ["kashi-vishwanath-temple", "sarnath-stupa"],
    isPopular: true,
    isHiddenGem: false
  },
  {
    id: "kashi-vishwanath-temple",
    name: "Kashi Vishwanath Temple",
    stateId: "uttar-pradesh",
    cityId: "varanasi",
    category: "Spiritual",
    tags: ["Jyotirlinga", "Lord Shiva", "Gold Dome", "Pilgrimage"],
    description: "One of the twelve sacred Jyotirlingas, located on the western bank of the Ganges in Varanasi with a gold-plated spire.",
    history: "Rebuilt by Maharani Ahilyabai Holkar in 1780; Maharaja Ranjit Singh donated 1 ton of pure gold for the spire in 1835.",
    bestTime: "October to March",
    timings: "03:00 AM - 11:00 PM (Daily)",
    entryFee: "Free general darshan. Special pooja passes available.",
    location: "Lahori Tola, Varanasi, Uttar Pradesh 221001",
    latitude: 25.3109,
    longitude: 83.0107,
    mapUrl: "https://maps.google.com/?q=25.3109,83.0107",
    image: "https://images.unsplash.com/photo-1561359313-0639aad49ca6?auto=format&fit=crop&w=1200&q=80",
    gallery: [],
    nearbyPlaces: ["dashashwamedh-ghat"],
    isPopular: true,
    isHiddenGem: false
  },
  {
    id: "bara-imambara",
    name: "Bara Imambara & Bhulbhulaiya",
    stateId: "uttar-pradesh",
    cityId: "lucknow",
    category: "Heritage",
    tags: ["Awadhi Architecture", "Labyrinth", "Nawabs", "Architecture"],
    description: "An architectural marvel built by Nawab Asaf-ud-Daula in 1784 featuring an immense column-less central hall and an intricate 3D labyrinth (Bhulbhulaiya).",
    history: "Commissioned as a famine relief project to provide employment to over 20,000 citizens during a severe draught in 1784.",
    bestTime: "October to March",
    timings: "06:00 AM - 05:00 PM (Closed on Mondays)",
    entryFee: "₹50 (Indians), ₹500 (Foreigners)",
    location: "Husainabad Trust Rd, Machchhi Bhavan, Lucknow, Uttar Pradesh 226003",
    latitude: 26.8692,
    longitude: 80.9131,
    mapUrl: "https://maps.google.com/?q=26.8692,80.9131",
    image: "https://images.unsplash.com/photo-1582510003544-4d00b7f74220?auto=format&fit=crop&w=1200&q=80",
    gallery: [],
    nearbyPlaces: ["chota-imambara", "rumi-darwaza"],
    isPopular: true,
    isHiddenGem: false
  },
  {
    id: "ram-mandir-ayodhya",
    name: "Shri Ram Janmabhoomi Mandir",
    stateId: "uttar-pradesh",
    cityId: "ayodhya",
    category: "Spiritual",
    tags: ["Lord Rama", "Nagara Style", "Sacred Pilgrimage", "Pink Sandstone"],
    description: "A grand temple built in traditional Nagara style architecture using pink Bansi Paharpur sandstone on the holy birthplace of Lord Rama.",
    history: "Consecrated in January 2024, constructed without iron or steel for a structural lifespan exceeding 1000 years.",
    bestTime: "October to March",
    timings: "06:30 AM - 12:00 PM & 02:00 PM - 09:30 PM (Daily)",
    entryFee: "Free general darshan. Pre-booking available.",
    location: "Sai Nagar, Ayodhya, Uttar Pradesh 224123",
    latitude: 26.7956,
    longitude: 82.1944,
    mapUrl: "https://maps.google.com/?q=26.7956,82.1944",
    image: "https://images.unsplash.com/photo-1548013146-72479768bada?auto=format&fit=crop&w=1200&q=80",
    gallery: [],
    nearbyPlaces: ["hanuman-garhi", "saryu-ghats"],
    isPopular: true,
    isHiddenGem: false
  },

  // --- Punjab ---
  {
    id: "golden-temple-amritsar",
    name: "Golden Temple (Sri Harmandir Sahib)",
    stateId: "punjab",
    cityId: "amritsar",
    category: "Spiritual",
    tags: ["Sikhism", "Golden Sanctum", "Amrit Sarovar", "Langar"],
    description: "The holiest Gurdwara of Sikhism surrounded by the sacred Amrit Sarovar lake, welcoming hundreds of thousands to its 24/7 free community kitchen (Langar).",
    history: "Founded in 1577 by Guru Ram Das; the sanctum was adorned with gold foil by Maharaja Ranjit Singh in 1830.",
    bestTime: "October to March (Illuminated at night)",
    timings: "Open 24 Hours (Daily)",
    entryFee: "Free for all visitors",
    location: "Golden Temple Rd, Atta Mandi, Amritsar, Punjab 143006",
    latitude: 31.6200,
    longitude: 74.8765,
    mapUrl: "https://maps.google.com/?q=31.6200,74.8765",
    image: "https://images.unsplash.com/photo-1588096344356-9a4f40f0a514?auto=format&fit=crop&w=1200&q=80",
    gallery: [
      "https://images.unsplash.com/photo-1582510003544-4d00b7f74220?auto=format&fit=crop&w=800&q=80"
    ],
    nearbyPlaces: ["jallianwala-bagh", "wagah-border"],
    isPopular: true,
    isHiddenGem: false
  },
  {
    id: "wagah-border",
    name: "Attari-Wagah Border Beating Retreat",
    stateId: "punjab",
    cityId: "amritsar",
    category: "Culture",
    tags: ["Patriotism", "Border Ceremony", "BSF", "National Pride"],
    description: "A synchronized military drill performed daily before sunset by the Indian Border Security Force (BSF) and Pakistan Rangers.",
    history: "Conducted every evening since 1959, famous for high-stepping parades, energetic anthems, and lowering of national flags.",
    bestTime: "October to March (Arrive by 03:30 PM for seats)",
    timings: "Ceremony starts at 04:30 PM in winter / 05:30 PM in summer",
    entryFee: "Free entry (Valid photo ID required)",
    location: "Grand Trunk Road, Attari, Punjab 143108 (30 km from Amritsar)",
    latitude: 31.6047,
    longitude: 74.5724,
    mapUrl: "https://maps.google.com/?q=31.6047,74.5724",
    image: "https://images.unsplash.com/photo-1532375810709-75b1da00537c?auto=format&fit=crop&w=1200&q=80",
    gallery: [],
    nearbyPlaces: ["golden-temple-amritsar"],
    isPopular: true,
    isHiddenGem: false
  },

  // --- Delhi (UT) ---
  {
    id: "qutub-minar",
    name: "Qutub Minar & Complex",
    stateId: "delhi",
    cityId: "delhi-city",
    category: "Heritage",
    tags: ["UNESCO", "Tower", "Sultanate", "Iron Pillar"],
    description: "A 72.5m high minaret of red sandstone and marble built starting in 1192, featuring the 1600-year-old rust-resistant Iron Pillar of Chandragupta II.",
    history: "Initiated by Qutb-ud-din Aibak and completed by Iltutmish; it represents the finest early Indo-Islamic architectural style in Delhi.",
    bestTime: "October to March",
    timings: "07:00 AM - 05:00 PM (Daily)",
    entryFee: "₹35 (Indians), ₹550 (Foreigners)",
    location: "Seth Sarai, Mehrauli, New Delhi, Delhi 110030",
    latitude: 28.5245,
    longitude: 77.1855,
    mapUrl: "https://maps.google.com/?q=28.5245,77.1855",
    image: "https://images.unsplash.com/photo-1545232979-fbf68fe9b10b?auto=format&fit=crop&w=1200&q=80",
    gallery: [],
    nearbyPlaces: ["humayuns-tomb", "red-fort-delhi", "india-gate"],
    isPopular: true,
    isHiddenGem: false
  },
  {
    id: "humayuns-tomb",
    name: "Humayun's Tomb",
    stateId: "delhi",
    cityId: "delhi-city",
    category: "Heritage",
    tags: ["UNESCO", "Charbagh", "Mughal Garden Tomb", "Precursor to Taj"],
    description: "The first garden-tomb on the Indian subcontinent, commissioned by Empress Bega Begum in 1558 with symmetrical Charbagh gardens.",
    history: "Designed by Persian architect Mirak Mirza Ghiyas, this UNESCO monument was the primary architectural inspiration for the Taj Mahal.",
    bestTime: "October to March (Late afternoon light)",
    timings: "06:00 AM - 06:00 PM (Daily)",
    entryFee: "₹35 (Indians), ₹550 (Foreigners)",
    location: "Mathura Rd, Nizamuddin East, New Delhi, Delhi 110013",
    latitude: 28.5933,
    longitude: 77.2507,
    mapUrl: "https://maps.google.com/?q=28.5933,77.2507",
    image: "https://images.unsplash.com/photo-1587474260584-136574528ed5?auto=format&fit=crop&w=1200&q=80",
    gallery: [],
    nearbyPlaces: ["qutub-minar", "india-gate"],
    isPopular: true,
    isHiddenGem: false
  },
  {
    id: "red-fort-delhi",
    name: "Red Fort (Lal Qila)",
    stateId: "delhi",
    cityId: "delhi-city",
    category: "Heritage",
    tags: ["UNESCO", "Mughal Fortress", "Independence Day", "Diwan-i-Khas"],
    description: "Historic red sandstone fortress constructed in 1639 by Emperor Shah Jahan when he shifted his capital to Shahjahanabad.",
    history: "Site of India's annual Independence Day flag hoisting by the Prime Minister; represents the zenith of Mughal creativity.",
    bestTime: "October to March",
    timings: "09:30 AM - 04:30 PM (Closed on Mondays)",
    entryFee: "₹35 (Indians), ₹500 (Foreigners)",
    location: "Netaji Subhash Marg, Chandni Chowk, New Delhi, Delhi 110006",
    latitude: 28.6562,
    longitude: 77.2410,
    mapUrl: "https://maps.google.com/?q=28.6562,77.2410",
    image: "https://images.unsplash.com/photo-1585130401366-fe05a8d813c4?auto=format&fit=crop&w=1200&q=80",
    gallery: [],
    nearbyPlaces: ["qutub-minar", "chandni-chowk"],
    isPopular: true,
    isHiddenGem: false
  },

  // ================= WEST INDIA =================
  // --- Rajasthan ---
  {
    id: "hawa-mahal",
    name: "Hawa Mahal",
    stateId: "rajasthan",
    cityId: "jaipur",
    category: "Heritage",
    tags: ["Palace", "Rajput", "Pink City", "Architecture"],
    description: "A five-storey palace built in 1799 by Maharaja Sawai Pratap Singh with 953 honeycomb-like intricately carved jharokhas.",
    history: "Designed in the form of Krishna's crown by Lal Chand Ustad so royal women could observe street life without being seen.",
    bestTime: "October to March (Early morning sunlight)",
    timings: "09:00 AM - 05:00 PM (Daily)",
    entryFee: "₹50 (Indians), ₹200 (Foreign Tourists)",
    location: "Hawa Mahal Rd, Badi Choupad, Pink City, Jaipur, Rajasthan 302002",
    latitude: 26.9239,
    longitude: 75.8267,
    mapUrl: "https://maps.google.com/?q=26.9239,75.8267",
    image: "https://images.unsplash.com/photo-1609137144813-7d9921338f24?auto=format&fit=crop&w=1200&q=80",
    gallery: [
      "https://images.unsplash.com/photo-1600100397608-f010f443905f?auto=format&fit=crop&w=800&q=80"
    ],
    nearbyPlaces: ["amber-fort", "city-palace-jaipur"],
    isPopular: true,
    isHiddenGem: false
  },
  {
    id: "amber-fort",
    name: "Amber Fort & Palace",
    stateId: "rajasthan",
    cityId: "jaipur",
    category: "Heritage",
    tags: ["Hill Fort", "UNESCO", "Sheesh Mahal", "Royal"],
    description: "Perched high on a hill overlooking Maota Lake, known for grand courtyards and the dazzling Sheesh Mahal (Mirror Palace).",
    history: "Constructed in 1592 by Raja Man Singh I; the palace was the principal residence of the Rajput Maharajas before Jaipur was built.",
    bestTime: "October to March",
    timings: "08:00 AM - 05:30 PM & 06:30 PM - 09:15 PM",
    entryFee: "₹100 (Indians), ₹550 (Foreign Tourists)",
    location: "Amer, Jaipur, Rajasthan 302001",
    latitude: 26.9855,
    longitude: 75.8513,
    mapUrl: "https://maps.google.com/?q=26.9855,75.8513",
    image: "https://images.unsplash.com/photo-1599661046289-e31897846e41?auto=format&fit=crop&w=1200&q=80",
    gallery: [],
    nearbyPlaces: ["hawa-mahal", "city-palace-jaipur"],
    isPopular: true,
    isHiddenGem: false
  },
  {
    id: "lake-palace-udaipur",
    name: "City Palace & Lake Pichola (Udaipur)",
    stateId: "rajasthan",
    cityId: "udaipur",
    category: "Romantic",
    tags: ["Lake Palace", "Mewar Royalty", "Sunset Boat Ride", "Architecture"],
    description: "A magnificent white marble palace complex overlooking the waters of Lake Pichola, housing courtyards, towers, and crystal galleries.",
    history: "Built over nearly 400 years starting in 1559 by Maharana Udai Singh II of the Sisodia Rajput clan.",
    bestTime: "October to March (Sunset boat cruise)",
    timings: "09:00 AM - 05:30 PM (Daily)",
    entryFee: "₹300 (Adults), ₹100 (Children). Boat rides extra.",
    location: "City Palace Complex, Udaipur, Rajasthan 313001",
    latitude: 24.5764,
    longitude: 73.6835,
    mapUrl: "https://maps.google.com/?q=24.5764,73.6835",
    image: "https://images.unsplash.com/photo-1615874959474-d609969a20ed?auto=format&fit=crop&w=1200&q=80",
    gallery: [],
    nearbyPlaces: ["jagmandir", "saheliyon-ki-bari"],
    isPopular: true,
    isHiddenGem: false
  },
  {
    id: "mehrangarh-fort",
    name: "Mehrangarh Fort & Museum",
    stateId: "rajasthan",
    cityId: "jodhpur",
    category: "Heritage",
    tags: ["Mighty Fortress", "Blue City", "Rathore Dynasty", "Museum"],
    description: "One of India's largest and most formidable hill forts, rising 120m above Jodhpur's blue city skyline with ornate palaces.",
    history: "Built in 1459 by Rao Jodha; the museum houses royal palanquins, turbans, and period miniature paintings.",
    bestTime: "October to March",
    timings: "09:00 AM - 05:00 PM (Daily)",
    entryFee: "₹100 (Indians), ₹600 (Foreigners)",
    location: "Fort Rd, Jodhpur, Rajasthan 342006",
    latitude: 26.2980,
    longitude: 73.0189,
    mapUrl: "https://maps.google.com/?q=26.2980,73.0189",
    image: "https://images.unsplash.com/photo-1579618218290-24a26f63a728?auto=format&fit=crop&w=1200&q=80",
    gallery: [],
    nearbyPlaces: ["jaswant-thada", "umaid-bhawan"],
    isPopular: true,
    isHiddenGem: false
  },

  // --- Maharashtra ---
  {
    id: "gateway-of-india",
    name: "Gateway of India & Marine Drive",
    stateId: "maharashtra",
    cityId: "mumbai",
    category: "Heritage",
    tags: ["Arabian Sea", "Indo-Saracenic", "Marine Drive", "Iconic Landmark"],
    description: "An iconic 26m arch monument overlooking Mumbai Harbour, built to commemorate the landing of King George V in 1911.",
    history: "Served as the symbolic departure point for the last British troops leaving India in 1948.",
    bestTime: "November to February (Evening for sunset sea breeze)",
    timings: "Open 24 Hours",
    entryFee: "Free access (Ferry to Elephanta Caves available)",
    location: "Apollo Bandar, Colaba, Mumbai, Maharashtra 400001",
    latitude: 18.9220,
    longitude: 72.8347,
    mapUrl: "https://maps.google.com/?q=18.9220,72.8347",
    image: "https://images.unsplash.com/photo-1567157577867-05ccb1388e66?auto=format&fit=crop&w=1200&q=80",
    gallery: [],
    nearbyPlaces: ["elephanta-caves", "marine-drive"],
    isPopular: true,
    isHiddenGem: false
  },
  {
    id: "kailash-temple-ellora",
    name: "Kailash Temple (Ellora Caves)",
    stateId: "maharashtra",
    cityId: "aurangabad",
    category: "Heritage",
    tags: ["Monolithic", "Rock Cut", "UNESCO", "Rashtrakuta"],
    description: "The world's largest monolithic rock-cut structure (Cave 16), carved entirely from top to bottom out of a single volcanic basalt cliff.",
    history: "Commissioned in the 8th century by Rashtrakuta King Krishna I; over 200,000 tonnes of rock were excavated by hand.",
    bestTime: "October to March",
    timings: "06:00 AM - 06:00 PM (Closed on Tuesdays)",
    entryFee: "₹40 (Indians), ₹600 (Foreigners)",
    location: "Ellora Caves, Chhatrapati Sambhajinagar, Maharashtra 431102",
    latitude: 20.0238,
    longitude: 75.1793,
    mapUrl: "https://maps.google.com/?q=20.0238,75.1793",
    image: "https://images.unsplash.com/photo-1590050752117-238cb0fb12b1?auto=format&fit=crop&w=1200&q=80",
    gallery: [],
    nearbyPlaces: ["ajanta-caves", "daulatabad-fort"],
    isPopular: true,
    isHiddenGem: false
  },

  // ================= SOUTH INDIA =================
  // --- Karnataka ---
  {
    id: "mysore-palace",
    name: "Mysore Palace (Amba Vilas)",
    stateId: "karnataka",
    cityId: "mysuru",
    category: "Heritage",
    tags: ["Wodeyar Dynasty", "Illumination", "Indo-Saracenic", "Palace"],
    description: "An Indo-Saracenic royal palace illuminated by over 97,000 bulbs every Sunday and during the famous 10-day Dasara festival.",
    history: "Completed in 1912 by architect Henry Irwin for the 24th ruler of the Wodeyar dynasty.",
    bestTime: "October to March (Sunday evening 7:00 PM for illumination)",
    timings: "10:00 AM - 05:30 PM (Daily). Illumination: Sundays 07:00 PM - 07:45 PM.",
    entryFee: "₹100 (Adults), ₹50 (Children), ₹200 (Foreigners)",
    location: "Sayyaji Rao Rd, Agrahara, Mysuru, Karnataka 570001",
    latitude: 12.3051,
    longitude: 76.6551,
    mapUrl: "https://maps.google.com/?q=12.3051,76.6551",
    image: "https://images.unsplash.com/photo-1600100397608-f010f443905f?auto=format&fit=crop&w=1200&q=80",
    gallery: [],
    nearbyPlaces: ["chamundi-hills", "brindavan-gardens"],
    isPopular: true,
    isHiddenGem: false
  },
  {
    id: "virupaksha-temple-hampi",
    name: "Virupaksha Temple & Stone Chariot (Hampi)",
    stateId: "karnataka",
    cityId: "hampi",
    category: "Heritage",
    tags: ["UNESCO", "Vijayanagara", "Ancient", "Stone Chariot"],
    description: "The 7th-century active Virupaksha Temple and the iconic stone chariot at Vittala Temple amidst boulder-strewn landscapes.",
    history: "Heart of the Vijayanagara Empire capital, which was the second largest city in the medieval world.",
    bestTime: "October to February",
    timings: "06:00 AM - 06:00 PM (Daily)",
    entryFee: "₹40 (Indians), ₹600 (Foreigners)",
    location: "Hampi, Vijayanagara District, Karnataka 583239",
    latitude: 15.3350,
    longitude: 76.4600,
    mapUrl: "https://maps.google.com/?q=15.3350,76.4600",
    image: "https://images.unsplash.com/photo-1599661046827-dacff0c0f09a?auto=format&fit=crop&w=1200&q=80",
    gallery: [],
    nearbyPlaces: ["lotus-mahal", "matanga-hill"],
    isPopular: true,
    isHiddenGem: false
  },

  // --- Kerala ---
  {
    id: "alleppey-backwaters",
    name: "Vembanad Backwaters & Houseboat Cruises",
    stateId: "kerala",
    cityId: "alleppey",
    category: "Nature",
    tags: ["Houseboat", "Lagoon", "Palm Trees", "Kerala Cuisine"],
    description: "A network of tranquil interconnected canals, lagoons, and lakes where traditional thatched wooden houseboats glide peacefully.",
    history: "Originally used as cargo vessels (kettuvallams) carrying rice and spices along the coast.",
    bestTime: "September to March",
    timings: "Houseboat cruises typically 12:00 PM to 09:00 AM next day.",
    entryFee: "Day cruise from ₹6000/boat; overnight from ₹10,000/boat.",
    location: "Finishing Point Road, Alappuzha, Kerala 688013",
    latitude: 9.4981,
    longitude: 76.3388,
    mapUrl: "https://maps.google.com/?q=9.4981,76.3388",
    image: "https://images.unsplash.com/photo-1602216056096-3b40cc0c9944?auto=format&fit=crop&w=1200&q=80",
    gallery: [],
    nearbyPlaces: ["marari-beach", "kumarakom"],
    isPopular: true,
    isHiddenGem: false
  },
  {
    id: "tea-gardens-munnar",
    name: "Kolukkumalai & Munnar Tea Estates",
    stateId: "kerala",
    cityId: "munnar",
    category: "Nature",
    tags: ["Tea Plantation", "Highest Organic Tea", "Misty Hills", "Sunrise"],
    description: "World's highest elevation tea plantation offering breathtaking views above the cloud line and sunrise over Western Ghats.",
    history: "Tea cultivation began in Munnar in the 1870s, transforming the valleys into verdant plantations.",
    bestTime: "September to May (Early morning jeep trek)",
    timings: "07:00 AM - 06:00 PM",
    entryFee: "₹100 (Tea Factory Tour). Jeep Safari charges apply.",
    location: "Munnar, Idukki District, Kerala 685612",
    latitude: 10.0889,
    longitude: 77.0595,
    mapUrl: "https://maps.google.com/?q=10.0889,77.0595",
    image: "https://images.unsplash.com/photo-1596401057633-54a8fe8ef647?auto=format&fit=crop&w=1200&q=80",
    gallery: [],
    nearbyPlaces: ["eravikulam-national-park", "mattupetty-dam"],
    isPopular: true,
    isHiddenGem: false
  },

  // --- Tamil Nadu ---
  {
    id: "meenakshi-temple-madurai",
    name: "Meenakshi Amman Temple",
    stateId: "tamil-nadu",
    cityId: "madurai",
    category: "Spiritual",
    tags: ["Dravidian", "Gopurams", "Hall of 1000 Pillars", "Ancient"],
    description: "A historic Hindu temple complex on the southern bank of the Vaigai River with 14 towering gateway gopurams covered in thousands of colorful stone figures.",
    history: "Mentioned in early Tamil literature; largely rebuilt between 1623 and 1655 by Tirumala Nayaka.",
    bestTime: "October to March (Evening ceremony at 09:00 PM)",
    timings: "05:00 AM - 12:30 PM & 04:00 PM - 10:00 PM (Daily)",
    entryFee: "Free general entry. ₹50 for Thousand Pillar Hall museum.",
    location: "Madurai Main, Madurai, Tamil Nadu 625001",
    latitude: 9.9195,
    longitude: 78.1193,
    mapUrl: "https://maps.google.com/?q=9.9195,78.1193",
    image: "https://images.unsplash.com/photo-1609137144813-7d9921338f24?auto=format&fit=crop&w=1200&q=80",
    gallery: [],
    nearbyPlaces: ["thirumalai-nayakkar-palace"],
    isPopular: true,
    isHiddenGem: false
  },

  // --- Ladakh & Kashmir ---
  {
    id: "pangong-lake",
    name: "Pangong Tso Lake",
    stateId: "ladakh",
    cityId: "pangong-tso",
    category: "Adventure",
    tags: ["Endorheic Lake", "High Altitude", "Himalayas", "Color Changing"],
    description: "A surreal high-altitude salt lake situated at 4,225m, famous for changing colors from shades of blue to green throughout the day.",
    history: "Formed millions of years ago when the Indian tectonic plate collided with Asia; the lake freezes completely in winter.",
    bestTime: "May to September",
    timings: "Open 24 Hours (Inner Line Permit required)",
    entryFee: "Ladakh Environment Fee ₹400",
    location: "Lukung / Spangmik, Leh Ladakh 194201",
    latitude: 33.7595,
    longitude: 78.6674,
    mapUrl: "https://maps.google.com/?q=33.7595,78.6674",
    image: "https://images.unsplash.com/photo-1581793745862-99fde7fa73d2?auto=format&fit=crop&w=1200&q=80",
    gallery: [],
    nearbyPlaces: ["nubra-valley", "khardung-la-pass"],
    isPopular: true,
    isHiddenGem: false
  },
  {
    id: "dal-lake-srinagar",
    name: "Dal Lake & Shikara Houseboats",
    stateId: "jammu-and-kashmir",
    cityId: "srinagar",
    category: "Romantic",
    tags: ["Houseboats", "Floating Market", "Shikara", "Mughal Gardens"],
    description: "The jewel of Srinagar featuring ornate handcrafted cedar houseboats, floating markets, and serene shikara boat rides.",
    history: "Celebrated by Mughal emperors Akbar and Jahangir, who built world-famous terraced royal gardens around its shoreline.",
    bestTime: "April to October & Dec to Feb (Snow)",
    timings: "06:00 AM - 08:00 PM for Shikara rides",
    entryFee: "Free lake entry (Shikara rides: ₹500 - ₹1000/hr)",
    location: "Boulevard Road, Dal Lake, Srinagar, Jammu & Kashmir 190001",
    latitude: 34.0837,
    longitude: 74.8370,
    mapUrl: "https://maps.google.com/?q=34.0837,74.8370",
    image: "https://images.unsplash.com/photo-1595815771614-ade9d652a65d?auto=format&fit=crop&w=1200&q=80",
    gallery: [],
    nearbyPlaces: ["shalimar-bagh", "nishat-bagh"],
    isPopular: true,
    isHiddenGem: false
  },

  // --- Northeast Wonders ---
  {
    id: "nohkalikai-falls",
    name: "Nohkalikai Falls & Living Root Bridges",
    stateId: "meghalaya",
    cityId: "cherrapunji",
    category: "Nature",
    tags: ["Waterfall", "Highest Plunge", "Root Bridge", "Trekking"],
    description: "India's highest plunge waterfall (340m) dropping into an emerald pool, combined with double-decker living root bridges.",
    history: "Root bridges are bio-engineered by Khasi villagers over centuries by guiding aerial roots of Ficus elastica trees across rivers.",
    bestTime: "September to May",
    timings: "08:00 AM - 05:00 PM",
    entryFee: "₹50 (Indians), ₹100 (Foreigners)",
    location: "Sohra (Cherrapunji), East Khasi Hills, Meghalaya 793108",
    latitude: 25.2756,
    longitude: 91.6853,
    mapUrl: "https://maps.google.com/?q=25.2756,91.6853",
    image: "https://images.unsplash.com/photo-1544735716-392fe2489ffa?auto=format&fit=crop&w=1200&q=80",
    gallery: [],
    nearbyPlaces: ["mawsmai-cave", "dawki-river"],
    isPopular: true,
    isHiddenGem: false
  },
  {
    id: "khaspur-silchar",
    name: "Khaspur Dimasa Kingdom Ruins (Silchar)",
    stateId: "assam",
    cityId: "silchar",
    category: "Heritage",
    tags: ["Dimasa Kingdom", "Ancient Fort", "Cachar", "Archaeology"],
    description: "The historic capital of the Dimasa Kachari rulers, featuring ancient brick gateway arches and Ranachandi Mandir dating back to 1750 AD.",
    history: "Preserves unique brick masonry blending Dimasa and Bengali architectural styles after the decline of Maibang.",
    bestTime: "October to March",
    timings: "09:00 AM - 05:00 PM (Daily)",
    entryFee: "Information unavailable (Free entry as per local tourism)",
    location: "Khaspur, Cachar District, Assam 788031 (20 km from Silchar)",
    latitude: 24.8333,
    longitude: 92.8000,
    mapUrl: "https://maps.google.com/?q=24.8333,92.8000",
    image: "https://images.unsplash.com/photo-1615874959474-d609969a20ed?auto=format&fit=crop&w=1200&q=80",
    gallery: [],
    nearbyPlaces: ["barak-river-view"],
    isPopular: false,
    isHiddenGem: true
  },
  {
    id: "kaziranga-safari",
    name: "Kaziranga Rhino Safari",
    stateId: "assam",
    cityId: "kaziranga",
    category: "Wildlife",
    tags: ["One-Horned Rhino", "UNESCO", "Jungle Safari", "Elephant Safari"],
    description: "World-renowned grasslands home to over 2,400 greater one-horned rhinos, tigers, wild water buffalo, and swamp deer.",
    history: "Established in 1905 through Mary Curzon's initiative; declared a UNESCO World Heritage Site in 1985.",
    bestTime: "November to April",
    timings: "Morning Safari: 07:30 AM - 10:00 AM | Afternoon: 01:30 PM - 03:30 PM",
    entryFee: "Jeep Safari: ₹2000-₹3500/vehicle",
    location: "Kaziranga, Golaghat District, Assam 785609",
    latitude: 26.5775,
    longitude: 93.1711,
    mapUrl: "https://maps.google.com/?q=26.5775,93.1711",
    image: "https://images.unsplash.com/photo-1561731216-c3a4d99437d5?auto=format&fit=crop&w=1200&q=80",
    gallery: [],
    nearbyPlaces: ["majuli-island"],
    isPopular: true,
    isHiddenGem: false
  },
  {
    id: "tawang-monastery",
    name: "Tawang Monastery (Galden Namgey Lhatse)",
    stateId: "arunachal-pradesh",
    cityId: "tawang",
    category: "Spiritual",
    tags: ["Tibetan Buddhism", "Highest Monastery", "Himalayas", "Heritage"],
    description: "India's largest monastery and the second largest in the world, perched at 3,048m surrounded by snowy peaks.",
    history: "Founded in 1680–1681 by Merak Lama Lodre Gyatso in accordance with the 5th Dalai Lama's wishes.",
    bestTime: "March to June & Sept to Nov",
    timings: "07:00 AM - 07:00 PM (Daily)",
    entryFee: "Free entry",
    location: "Tawang, Arunachal Pradesh 790104",
    latitude: 27.5861,
    longitude: 91.8594,
    mapUrl: "https://maps.google.com/?q=27.5861,91.8594",
    image: "https://images.unsplash.com/photo-1626621341517-bbf3d9990a23?auto=format&fit=crop&w=1200&q=80",
    gallery: [],
    nearbyPlaces: ["sela-pass", "madhuri-lake"],
    isPopular: true,
    isHiddenGem: true
  },
  {
    id: "cellular-jail-andaman",
    name: "Cellular Jail National Memorial (Kala Pani)",
    stateId: "andaman-and-nicobar",
    cityId: "port-blair",
    category: "Heritage",
    tags: ["Freedom Struggle", "Historical", "Sound and Light", "National Memorial"],
    description: "Colonial prison used to exile freedom fighters, famous for its radial architecture and moving Sound & Light show.",
    history: "Constructed between 1896 and 1906, it housed revered revolutionaries including Veer Savarkar.",
    bestTime: "October to May",
    timings: "09:00 AM - 12:30 PM & 01:30 PM - 04:45 PM (Closed on Mondays)",
    entryFee: "₹30 (Museum), ₹50-₹150 (Sound & Light Show)",
    location: "Atlanta Point, Port Blair, Andaman and Nicobar Islands 744104",
    latitude: 11.6739,
    longitude: 92.7478,
    mapUrl: "https://maps.google.com/?q=11.6739,92.7478",
    image: "https://images.unsplash.com/photo-1589308078059-be1415eab4c3?auto=format&fit=crop&w=1200&q=80",
    gallery: [],
    nearbyPlaces: ["havelock-island"],
    isPopular: true,
    isHiddenGem: false
  },
  {
    id: "radhanagar-beach-havelock",
    name: "Radhanagar Beach (Beach No. 7)",
    stateId: "andaman-and-nicobar",
    cityId: "havelock",
    category: "Beaches",
    tags: ["Asia Top Beach", "White Sand", "Turquoise Water", "Sunset"],
    description: "Renowned for soft powdery white sand, lush rainforest backdrop, pristine turquoise water, and tropical sunsets.",
    history: "Awarded 'Asia's Best Beach' by Time Magazine and holds international Blue Flag eco certification.",
    bestTime: "October to May",
    timings: "06:00 AM - 05:30 PM",
    entryFee: "Free access",
    location: "Havelock Island (Swaraj Dweep), Andaman & Nicobar Islands 744211",
    latitude: 11.9840,
    longitude: 92.9510,
    mapUrl: "https://maps.google.com/?q=11.9840,92.9510",
    image: "https://images.unsplash.com/photo-1512343879784-a960bf40e7f2?auto=format&fit=crop&w=1200&q=80",
    gallery: [],
    nearbyPlaces: ["elephant-beach"],
    isPopular: true,
    isHiddenGem: false
  }
];