/**
 * TRAVELBHARAT - STATES & UNION TERRITORIES DATA
 * Complete list of all 28 States and 8 Union Territories in India
 * Every State and UT has a unique, verified high-resolution photo.
 */

const TravelBharatStates = [
  // --- North India ---
  {
    id: "himachal-pradesh",
    name: "Himachal Pradesh",
    type: "state",
    region: "North",
    capital: "Shimla (Summer), Dharamshala (Winter)",
    tagline: "The Land of the Gods and Snow-Capped Peaks",
    overview: "Nestled in the western Himalayas, Himachal Pradesh is celebrated for dramatic mountain landscapes, pine valleys, ancient temples, and vibrant adventure sports.",
    bestTimeToVisit: "March to June (Summer) & October to February (Snowfall)",
    popularDishes: ["Dham", "Siddu", "Chha Gosht", "Madra"],
    majorAirports: ["Kullu-Manali (KUU)", "Kangra-Gaggal (DHM)", "Shimla (SLV)"],
    bannerImage: "https://images.unsplash.com/photo-1626621341517-bbf3d9990a23?auto=format&fit=crop&w=1200&q=80"
  },
  {
    id: "uttarakhand",
    name: "Uttarakhand",
    type: "state",
    region: "North",
    capital: "Dehradun (Winter), Gairsain (Summer)",
    tagline: "Devbhumi – The Abode of the Gods",
    overview: "Home to the revered Char Dham pilgrimage, sacred Ganges origins, majestic Himalayan trekking routes, and scenic hill retreats like Mussoorie and Nainital.",
    bestTimeToVisit: "March to June & September to November",
    popularDishes: ["Kafuli", "Aloo ke Gutke", "Bhatt ki Churkani", "Bal Mithai"],
    majorAirports: ["Jolly Grant Dehradun (DED)", "Pantnagar (PGH)"],
    bannerImage: "https://images.unsplash.com/photo-1518002171953-a080ee817e1f?auto=format&fit=crop&w=1200&q=80"
  },
  {
    id: "punjab",
    name: "Punjab",
    type: "state",
    region: "North",
    capital: "Chandigarh",
    tagline: "The Land of Five Rivers and Golden Hospitality",
    overview: "Famed for the iconic Golden Temple in Amritsar, lush mustard fields, spirited Bhangra folk arts, and world-renowned culinary traditions.",
    bestTimeToVisit: "October to March",
    popularDishes: ["Makki di Roti & Sarson da Saag", "Butter Chicken", "Amritsari Kulcha", "Lassi"],
    majorAirports: ["Sri Guru Ram Dass Jee Amritsar (ATQ)", "Chandigarh (IXC)"],
    bannerImage: "https://images.unsplash.com/photo-1588096344356-9a4f40f0a514?auto=format&fit=crop&w=1200&q=80"
  },
  {
    id: "haryana",
    name: "Haryana",
    type: "state",
    region: "North",
    capital: "Chandigarh",
    tagline: "Cradle of Ancient Civilizations and Epic Heritage",
    overview: "Surrounding the national capital, Haryana blends ancient Mahabharata battlegrounds at Kurukshetra with modern corporate hubs and highway culinary traditions.",
    bestTimeToVisit: "October to March",
    popularDishes: ["Bajra Khichdi", "Kadhi Pakora", "Singri ki Sabzi", "Ghevar"],
    majorAirports: ["Indira Gandhi International Delhi (DEL - Adjacent)"],
    bannerImage: "https://images.unsplash.com/photo-1500382017468-9049fed747ef?auto=format&fit=crop&w=1200&q=80"
  },
  {
    id: "uttar-pradesh",
    name: "Uttar Pradesh",
    type: "state",
    region: "North",
    capital: "Lucknow",
    tagline: "The Heartland of Indian Heritage, Faith and Wonders",
    overview: "Home to the world wonder Taj Mahal in Agra, the eternal spiritual ghats of Varanasi, the sacred Ayodhya and Mathura, and the Nawabi elegance of Lucknow.",
    bestTimeToVisit: "October to March",
    popularDishes: ["Awadhi Biryani", "Galouti Kebab", "Banarasi Paan", "Peda"],
    majorAirports: ["Lucknow (LKO)", "Varanasi (VNS)", "Noida Jewar (Upcoming)", "Ayodhya (AYJ)"],
    bannerImage: "https://images.unsplash.com/photo-1564507592333-c60657eea523?auto=format&fit=crop&w=1200&q=80"
  },

  // --- West India ---
  {
    id: "rajasthan",
    name: "Rajasthan",
    type: "state",
    region: "West",
    capital: "Jaipur",
    tagline: "The Land of Kings, Forts, and Desert Magic",
    overview: "India's desert jewel adorned with colossal hill forts, ornate royal palaces, vibrant bazaars, camel caravans in the Thar Desert, and regal Rajasthani hospitality.",
    bestTimeToVisit: "October to March",
    popularDishes: ["Dal Baati Churma", "Laal Maas", "Gatte ki Sabzi", "Pyaaz Kachori"],
    majorAirports: ["Jaipur (JAI)", "Udaipur (UDR)", "Jodhpur (JDH)", "Jaisalmer (JSA)"],
    bannerImage: "https://images.unsplash.com/photo-1599661046289-e31897846e41?auto=format&fit=crop&w=1200&q=80"
  },
  {
    id: "gujarat",
    name: "Gujarat",
    type: "state",
    region: "West",
    capital: "Gandhinagar",
    tagline: "Vibrant Land of White Rann, Lions and Heritage",
    overview: "Home to the surreal white salt desert of the Rann of Kutch, the Asiatic Lions of Gir, Mahatma Gandhi's Sabarmati Ashram, and the colossal Statue of Unity.",
    bestTimeToVisit: "November to February (Rann Utsav)",
    popularDishes: ["Dhokla", "Thepla", "Undhiyu", "Gujarati Thali", "Khandvi"],
    majorAirports: ["Sardar Vallabhbhai Patel Ahmedabad (AMD)", "Surat (STV)", "Vadodara (BDQ)"],
    bannerImage: "https://images.unsplash.com/photo-1509316975850-ff9c5deb0cd9?auto=format&fit=crop&w=1200&q=80"
  },
  {
    id: "maharashtra",
    name: "Maharashtra",
    type: "state",
    region: "West",
    capital: "Mumbai",
    tagline: "Gateway of India, Sahyadri Forts and Coastal Beauty",
    overview: "A dynamic powerhouse boasting Mumbai's bustling coastal energy, the UNESCO Ajanta & Ellora cave temples, Pune's Maratha history, and lush Western Ghat hill stations.",
    bestTimeToVisit: "September to March",
    popularDishes: ["Vada Pav", "Misal Pav", "Puran Poli", "Pithla Bhakri", "Bombil Fry"],
    majorAirports: ["Chhatrapati Shivaji Maharaj Mumbai (BOM)", "Pune (PNQ)", "Nagpur (NAG)"],
    bannerImage: "https://images.unsplash.com/photo-1567157577867-05ccb1388e66?auto=format&fit=crop&w=1200&q=80"
  },
  {
    id: "goa",
    name: "Goa",
    type: "state",
    region: "West",
    capital: "Panaji",
    tagline: "Pearl of the Orient, Golden Sands and Portuguese Charm",
    overview: "India's premier coastal haven renowned for its sun-soaked beaches, Portuguese baroque churches, vibrant spice plantations, nightlife, and seafood cuisine.",
    bestTimeToVisit: "November to March",
    popularDishes: ["Goan Fish Curry", "Pork Vindaloo", "Bebinca", "Prawn Balchão"],
    majorAirports: ["Dabolim (GOI)", "Manohar International Airport Mopa (GOX)"],
    bannerImage: "https://images.unsplash.com/photo-1512343879784-a960bf40e7f2?auto=format&fit=crop&w=1200&q=80"
  },

  // --- South India ---
  {
    id: "karnataka",
    name: "Karnataka",
    type: "state",
    region: "South",
    capital: "Bengaluru",
    tagline: "One State, Many Worlds",
    overview: "From the tech capital of Bengaluru to the majestic ruins of the Vijayanagara Empire at Hampi, royal Mysuru, and the misty coffee hills of Coorg.",
    bestTimeToVisit: "October to March",
    popularDishes: ["Bisi Bele Bath", "Mysore Pak", "Neer Dosa", "Coorg Pandi Curry", "Rava Idli"],
    majorAirports: ["Kempegowda Bengaluru (BLR)", "Mangaluru (IXE)", "Belagavi (IXG)"],
    bannerImage: "https://images.unsplash.com/photo-1600100397608-f010f443905f?auto=format&fit=crop&w=1200&q=80"
  },
  {
    id: "kerala",
    name: "Kerala",
    type: "state",
    region: "South",
    capital: "Thiruvananthapuram",
    tagline: "God's Own Country",
    overview: "A tropical paradise of serene backwaters in Alleppey, rolling emerald tea estates in Munnar, Ayurvedic sanctuaries, and Kathakali cultural performances.",
    bestTimeToVisit: "September to March",
    popularDishes: ["Appam with Ishtu", "Kerala Sadya", "Karimeen Pollichathu", "Puttu and Kadala"],
    majorAirports: ["Cochin (COK)", "Trivandrum (TRV)", "Calicut (CCJ)", "Kannur (CNN)"],
    bannerImage: "https://images.unsplash.com/photo-1602216056096-3b40cc0c9944?auto=format&fit=crop&w=1200&q=80"
  },
  {
    id: "tamil-nadu",
    name: "Tamil Nadu",
    type: "state",
    region: "South",
    capital: "Chennai",
    tagline: "Enchanting Land of Dravidian Gopurams and Living Temples",
    overview: "A bastion of classical Dravidian culture, towering temple gopurams in Madurai and Thanjavur, seaside rock monuments at Mahabalipuram, and Nilgiri hill towns.",
    bestTimeToVisit: "November to March",
    popularDishes: ["Chettinad Chicken", "Masala Dosa", "Filter Coffee", "Pongal", "Kothu Parotta"],
    majorAirports: ["Chennai (MAA)", "Coimbatore (CJB)", "Madurai (IXM)", "Tiruchirappalli (TRZ)"],
    bannerImage: "https://images.unsplash.com/photo-1582510003544-4d00b7f74220?auto=format&fit=crop&w=1200&q=80"
  },
  {
    id: "andhra-pradesh",
    name: "Andhra Pradesh",
    type: "state",
    region: "South",
    capital: "Amaravati",
    tagline: "The Land of Lord Venkateswara and Coastal Marvels",
    overview: "Known for the sacred Tirupati temple hill, the picturesque Araku Valley, the Buddhist heritage of Amaravati, and Vizag's scenic eastern coastline.",
    bestTimeToVisit: "October to March",
    popularDishes: ["Hyderabadi/Andhra Spicy Biryani", "Pesarattu", "Gongura Pachadi", "Pootharekulu"],
    majorAirports: ["Visakhapatnam (VTZ)", "Vijayawada (VGA)", "Tirupati (TIR)"],
    bannerImage: "https://images.unsplash.com/photo-1548013146-72479768bada?auto=format&fit=crop&w=1200&q=80"
  },
  {
    id: "telangana",
    name: "Telangana",
    type: "state",
    region: "South",
    capital: "Hyderabad",
    tagline: "Where Royal Nizami Grandeur Meets Modern Tech",
    overview: "Celebrated for Hyderabad's 400-year-old Charminar, the opulent Chowmahalla Palace, Golconda Fort, and the exquisite Kakatiya architecture at Warangal.",
    bestTimeToVisit: "October to March",
    popularDishes: ["Hyderabadi Dum Biryani", "Haleem", "Mirchi ka Salan", "Qubani ka Meetha"],
    majorAirports: ["Rajiv Gandhi International Hyderabad (HYD)"],
    bannerImage: "https://images.unsplash.com/photo-1605335198270-424a52003cba?auto=format&fit=crop&w=1200&q=80"
  },

  // --- East India ---
  {
    id: "west-bengal",
    name: "West Bengal",
    type: "state",
    region: "East",
    capital: "Kolkata",
    tagline: "The Cultural Capital of Joy and Sundarbans Tigers",
    overview: "From the grand Victoria Memorial and Durga Puja celebrations in Kolkata to the Himalayan tea hills of Darjeeling and the mangrove tiger trails of the Sundarbans.",
    bestTimeToVisit: "October to March",
    popularDishes: ["Kosha Mangsho", "Macher Jhol", "Rosogolla", "Mishti Doi", "Kathi Roll"],
    majorAirports: ["Netaji Subhash Chandra Bose Kolkata (CCU)", "Bagdogra (IXB)"],
    bannerImage: "https://images.unsplash.com/photo-1558431382-27e303142255?auto=format&fit=crop&w=1200&q=80"
  },
  {
    id: "odisha",
    name: "Odisha",
    type: "state",
    region: "East",
    capital: "Bhubaneswar",
    tagline: "India's Best Kept Secret – Temples, Dance and Coast",
    overview: "Home to the Sun Temple at Konark, the sacred Jagannath Temple in Puri, Asia's largest brackish lagoon at Chilika Lake, and ancient Odissi dance art.",
    bestTimeToVisit: "October to March",
    popularDishes: ["Chhena Poda", "Dalma", "Pakhala Bhata", "Khaja"],
    majorAirports: ["Biju Patnaik Bhubaneswar (BBI)", "Jharsuguda (JRG)"],
    bannerImage: "https://images.unsplash.com/photo-1608889825103-eb5ed706fc64?auto=format&fit=crop&w=1200&q=80"
  },
  {
    id: "bihar",
    name: "Bihar",
    type: "state",
    region: "East",
    capital: "Patna",
    tagline: "Land of Buddha's Enlightenment and Ancient Nalanda",
    overview: "The cradle of Buddhism and Jainism, featuring the sacred Mahabodhi Temple in Bodh Gaya, the ruins of ancient Nalanda University, and Rajgir's peace stupa.",
    bestTimeToVisit: "October to March",
    popularDishes: ["Litti Chokha", "Sattu Paratha", "Khaja", "Thekua"],
    majorAirports: ["Jay Prakash Narayan Patna (PAT)", "Gaya (GAY)"],
    bannerImage: "https://images.unsplash.com/photo-1571536802807-30451e3955d8?auto=format&fit=crop&w=1200&q=80"
  },
  {
    id: "jharkhand",
    name: "Jharkhand",
    type: "state",
    region: "East",
    capital: "Ranchi",
    tagline: "The Land of Waterfalls and Tribal Wilderness",
    overview: "Rich in lush forests, cascading waterfalls around Ranchi like Hundru and Jonha, Betla National Park, and holy pilgrimage shrines at Deoghar.",
    bestTimeToVisit: "October to March",
    popularDishes: ["Dhuska", "Rugra", "Chilka Roti", "Malpua"],
    majorAirports: ["Birsa Munda Ranchi (IXR)", "Deoghar (DGH)"],
    bannerImage: "https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=1200&q=80"
  },

  // --- Central India ---
  {
    id: "madhya-pradesh",
    name: "Madhya Pradesh",
    type: "state",
    region: "Central",
    capital: "Bhopal",
    tagline: "The Heart of Incredible India – Tigers and Heritage",
    overview: "Famous for the erotic Khajuraho temples, the Sanchi Buddhist stupa, the grand fort of Gwalior, and world-class tiger reserves like Kanha, Bandhavgarh, and Pench.",
    bestTimeToVisit: "October to April",
    popularDishes: ["Poha Jalebi", "Bhutte Ka Kees", "Dal Bafla", "Mawa Bati"],
    majorAirports: ["Raja Bhoj Bhopal (BHO)", "Devi Ahilyabai Holkar Indore (IDR)", "Gwalior (GWL)", "Jabalpur (JLR)"],
    bannerImage: "https://images.unsplash.com/photo-1590050752117-238cb0fb12b1?auto=format&fit=crop&w=1200&q=80"
  },
  {
    id: "chhattisgarh",
    name: "Chhattisgarh",
    type: "state",
    region: "Central",
    capital: "Raipur",
    tagline: "The Niagara of India and Ancient Bastar Tribal Culture",
    overview: "Celebrated for the horseshoe Chitrakote Waterfalls, ancient cave systems in Kanger Valley, and rich Bastar metalcraft and tribal dance traditions.",
    bestTimeToVisit: "October to March",
    popularDishes: ["Chila", "Farra", "Muthia", "Angakar Roti"],
    majorAirports: ["Swami Vivekananda Raipur (RPR)", "Bilaspur (PAB)"],
    bannerImage: "https://images.unsplash.com/photo-1544735716-392fe2489ffa?auto=format&fit=crop&w=1200&q=80"
  },

  // --- Northeast India ---
  {
    id: "assam",
    name: "Assam",
    type: "state",
    region: "Northeast",
    capital: "Dispur",
    tagline: "Land of the Red River, Blue Hills and One-Horned Rhinos",
    overview: "The gateway to Northeast India, famous for Kaziranga National Park's rhinos, world-famous Assam tea estates, the mighty Brahmaputra river, and Kamakhya Temple.",
    bestTimeToVisit: "November to April",
    popularDishes: ["Khaar", "Masor Tenga", "Duck Curry with Ash Gourd", "Pitha"],
    majorAirports: ["Lokpriya Gopinath Bordoloi Guwahati (GAU)", "Dibrugarh (DIB)", "Silchar (IXS)"],
    bannerImage: "https://images.unsplash.com/photo-1561731216-c3a4d99437d5?auto=format&fit=crop&w=1200&q=80"
  },
  {
    id: "meghalaya",
    name: "Meghalaya",
    type: "state",
    region: "Northeast",
    capital: "Shillong",
    tagline: "The Abode of Clouds and Living Root Bridges",
    overview: "An enchanting paradise featuring Cherrapunji's waterfalls, the double-decker living root bridges of Nongriat, Mawlynnong (Asia's cleanest village), and crystal-clear Umngot river.",
    bestTimeToVisit: "September to May",
    popularDishes: ["Jadoh", "Dohneiiong", "Tungrymbai", "Pukhlein"],
    majorAirports: ["Umroi Shillong (SHL)", "Guwahati Airport (GAU - 120km)"],
    bannerImage: "https://images.unsplash.com/photo-1511497584788-87676104235f?auto=format&fit=crop&w=1200&q=80"
  },
  {
    id: "arunachal-pradesh",
    name: "Arunachal Pradesh",
    type: "state",
    region: "Northeast",
    capital: "Itanagar",
    tagline: "Land of the Dawn-Lit Mountains",
    overview: "India's easternmost frontier with high-altitude lakes at Sela Pass, the magnificent 400-year-old Tawang Monastery, and untouched Himalayan valleys.",
    bestTimeToVisit: "October to April",
    popularDishes: ["Thukpa", "Momo", "Zan", "Pika Pila", "Apong"],
    majorAirports: ["Donyi Polo Airport Itanagar (HGI)", "Pasighat (IXT)"],
    bannerImage: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=1200&q=80"
  },
  {
    id: "sikkim",
    name: "Sikkim",
    type: "state",
    region: "Northeast",
    capital: "Gangtok",
    tagline: "Himalayan Sanctuary in the Shadow of Mt. Kanchenjunga",
    overview: "India's first fully organic state, known for Gangtok's vibrant mountain culture, serene Gurudongmar Lake, Yumthang Valley of Flowers, and Rumtek Monastery.",
    bestTimeToVisit: "March to May & October to December",
    popularDishes: ["Momos", "Thukpa", "Gundruk", "Phagshapa", "Chhurpi Soup"],
    majorAirports: ["Pakyong Airport Gangtok (PYG)", "Bagdogra (IXB - 120km)"],
    bannerImage: "https://images.unsplash.com/photo-1579618218290-24a26f63a728?auto=format&fit=crop&w=1200&q=80"
  },
  {
    id: "nagaland",
    name: "Nagaland",
    type: "state",
    region: "Northeast",
    capital: "Kohima",
    tagline: "Land of Festivals, Tribal Bravery and Dzukou Valley",
    overview: "Famed for the vibrant Hornbill Festival, the trekker's paradise at Dzukou Valley, traditional Naga longhouses, and indigenous warrior history.",
    bestTimeToVisit: "October to May (Hornbill in December)",
    popularDishes: ["Smoked Pork with Bamboo Shoot", "Axone", "Galho", "Zutho"],
    majorAirports: ["Dimapur Airport (DMU)"],
    bannerImage: "https://images.unsplash.com/photo-1532375810709-75b1da00537c?auto=format&fit=crop&w=1200&q=80"
  },
  {
    id: "manipur",
    name: "Manipur",
    type: "state",
    region: "Northeast",
    capital: "Imphal",
    tagline: "Jeweled Land of the Floating Loktak Lake",
    overview: "Home to the world's only floating national park (Keibul Lamjao) on Loktak Lake, the endangered Sangai brow-antlered deer, and classical Manipuri Rasleela dance.",
    bestTimeToVisit: "October to April",
    popularDishes: ["Kangshoi", "Eromba", "Singju", "Chak-hao Kheer (Black Rice)"],
    majorAirports: ["Bir Tikendrajit Imphal (IMF)"],
    bannerImage: "https://images.unsplash.com/photo-1615874959474-d609969a20ed?auto=format&fit=crop&w=1200&q=80"
  },
  {
    id: "mizoram",
    name: "Mizoram",
    type: "state",
    region: "Northeast",
    capital: "Aizawl",
    tagline: "Land of Rolling Blue Hills and Cheraw Bamboo Dance",
    overview: "A picturesque haven of undulating hills, steep bamboo valleys, Reiek Tlang mountain viewpoints, and welcoming Mizo cultural communities.",
    bestTimeToVisit: "October to March",
    popularDishes: ["Bai", "Vawksa Rep", "Sawhchiar", "Sanpiau"],
    majorAirports: ["Lengpui Airport Aizawl (AJL)"],
    bannerImage: "https://images.unsplash.com/photo-1586348943529-beaae6c28db9?auto=format&fit=crop&w=1200&q=80"
  },
  {
    id: "tripura",
    name: "Tripura",
    type: "state",
    region: "Northeast",
    capital: "Agartala",
    tagline: "Palaces of Ujjayanta and Mysterious Unakoti Sculptures",
    overview: "Famous for the water-palace Neermahal in the middle of Rudrasagar Lake, the royal Ujjayanta Palace, and the colossal rock carvings of Unakoti.",
    bestTimeToVisit: "October to March",
    popularDishes: ["Mui Borok", "Chakhwi", "Mosdeng Serma", "Bhangui"],
    majorAirports: ["Maharaja Bir Bikram Agartala (IXA)"],
    bannerImage: "https://images.unsplash.com/photo-1599661046827-dacff0c0f09a?auto=format&fit=crop&w=1200&q=80"
  },

  // --- Union Territories (8 UTs) ---
  {
    id: "delhi",
    name: "Delhi (NCT)",
    type: "ut",
    region: "UT",
    capital: "New Delhi",
    tagline: "The Historical and Sovereign Heart of India",
    overview: "A vibrant metropolis where millennia of empires (Mughal Red Fort, Qutub Minar, Humayun's Tomb) seamlessly meet modern governance and iconic street cuisines.",
    bestTimeToVisit: "October to March",
    popularDishes: ["Chole Bhature", "Butter Chicken", "Chaat", "Nihari", "Paranthas"],
    majorAirports: ["Indira Gandhi International Airport (DEL)"],
    bannerImage: "https://images.unsplash.com/photo-1587474260584-136574528ed5?auto=format&fit=crop&w=1200&q=80"
  },
  {
    id: "ladakh",
    name: "Ladakh",
    type: "ut",
    region: "UT",
    capital: "Leh",
    tagline: "The Land of High Passes and Azure Alpine Lakes",
    overview: "A surreal high-altitude cold desert featuring Pangong Tso's color-shifting waters, Nubra Valley's sand dunes, Khardung La pass, and ancient Tibetan monasteries.",
    bestTimeToVisit: "May to September",
    popularDishes: ["Skyu", "Thukpa", "Butter Tea (Gur Gur Chai)", "Tingmo"],
    majorAirports: ["Kushok Bakula Rimpochee Leh (IXL)"],
    bannerImage: "https://images.unsplash.com/photo-1581793745862-99fde7fa73d2?auto=format&fit=crop&w=1200&q=80"
  },
  {
    id: "jammu-and-kashmir",
    name: "Jammu and Kashmir",
    type: "ut",
    region: "UT",
    capital: "Srinagar (Summer), Jammu (Winter)",
    tagline: "Paradise on Earth – Dal Lake, Gulmarg and Shikhara Charms",
    overview: "World-renowned for Srinagar's Dal Lake houseboats, Gulmarg's snow-clad ski slopes, the meadows of Pahalgam, and the revered Vaishno Devi shrine.",
    bestTimeToVisit: "April to October (Spring/Summer) & December to February (Snow)",
    popularDishes: ["Rogan Josh", "Wazwan", "Kahwa Tea", "Modur Pulao", "Dum Aloo"],
    majorAirports: ["Sheikh ul-Alam Srinagar (SXR)", "Jammu Airport (IXJ)"],
    bannerImage: "https://images.unsplash.com/photo-1595815771614-ade9d652a65d?auto=format&fit=crop&w=1200&q=80"
  },
  {
    id: "andaman-and-nicobar",
    name: "Andaman and Nicobar Islands",
    type: "ut",
    region: "UT",
    capital: "Port Blair",
    tagline: "Emerald Archipelago of Radhanagar Beach and Coral Reefs",
    overview: "Pristine tropical islands in the Bay of Bengal with crystal-clear turquoise waters at Havelock Island, scuba diving among coral reefs, and the historic Cellular Jail.",
    bestTimeToVisit: "November to May",
    popularDishes: ["Fish Curry", "Chilli Curry", "Coconut Prawn Curry", "Grilled Lobster"],
    majorAirports: ["Veer Savarkar International Port Blair (IXZ)"],
    bannerImage: "https://images.unsplash.com/photo-1589308078059-be1415eab4c3?auto=format&fit=crop&w=1200&q=80"
  },
  {
    id: "chandigarh",
    name: "Chandigarh",
    type: "ut",
    region: "UT",
    capital: "Chandigarh",
    tagline: "The Beautiful City Planned by Le Corbusier",
    overview: "India's first planned modernist city, renowned for Nek Chand's Rock Garden, serene Sukhna Lake, wide tree-lined boulevards, and sprawling Rose Garden.",
    bestTimeToVisit: "October to March",
    popularDishes: ["Amritsari Kulcha", "Lassi", "Butter Chicken", "Chole Puri"],
    majorAirports: ["Shaheed Bhagat Singh Chandigarh Airport (IXC)"],
    bannerImage: "https://images.unsplash.com/photo-1596401057633-54a8fe8ef647?auto=format&fit=crop&w=1200&q=80"
  },
  {
    id: "puducherry",
    name: "Puducherry",
    type: "ut",
    region: "UT",
    capital: "Pondicherry",
    tagline: "French Riviera of the East and Auroville Peace",
    overview: "Charming French colonial heritage with pastel villas, bougainvillea streets in White Town, seaside promenade, and the spiritual community of Auroville.",
    bestTimeToVisit: "October to March",
    popularDishes: ["Crepes", "Croissants", "Bouillabaisse", "Kadugu Yerra", "Ratatouille"],
    majorAirports: ["Puducherry Airport (PNY)", "Chennai Airport (MAA - 150km)"],
    bannerImage: "https://images.unsplash.com/photo-1570168007204-dfb528c6958f?auto=format&fit=crop&w=1200&q=80"
  },
  {
    id: "lakshadweep",
    name: "Lakshadweep",
    type: "ut",
    region: "UT",
    capital: "Kavaratti",
    tagline: "Secluded Coral Atolls and Bioluminescent Lagoons",
    overview: "A secluded paradise of 36 coral islands in the Arabian Sea, boasting pristine crystal lagoons at Agatti and Bangaram, rich marine life, and tranquil island living.",
    bestTimeToVisit: "October to May",
    popularDishes: ["Mus Kavaab", "Fish Tikka", "Coconut Rice", "Rayereha"],
    majorAirports: ["Agatti Airport (AGX)"],
    bannerImage: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=1200&q=80"
  },
  {
    id: "dadra-and-nagar-haveli-and-daman-and-diu",
    name: "Dadra & Nagar Haveli and Daman & Diu",
    type: "ut",
    region: "UT",
    capital: "Daman",
    tagline: "Coastal Forts, Portuguese Churches and Tranquil Seas",
    overview: "A picturesque coastal union territory featuring Diu's sea-facing fortress, Daman's historic churches and black-sand Devka Beach, and Silvassa's tribal museums.",
    bestTimeToVisit: "October to April",
    popularDishes: ["Seafood Platter", "Parsi Fish Curry", "Dhokla", "Portuguese Roast Chicken"],
    majorAirports: ["Diu Airport (DIU)", "Surat Airport (STV - 110km)"],
    bannerImage: "https://images.unsplash.com/photo-1544735716-392fe2489ffa?auto=format&fit=crop&w=1200&q=80"
  }
];
